include(GNUInstallDirs)

set(KS_INSTALL_DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/${PROJECT_NAME})
set(KS_INSTALL_INCLUDE ${CMAKE_INSTALL_FULL_INCLUDEDIR}/${PROJECT_NAME})
set(KS_INSTALL_TRANSLATIONDIR ${KS_INSTALL_DATADIR}/translations)
set(KS_INSTALL_PLUGINDIR ${CMAKE_INSTALL_FULL_LIBDIR}/${PROJECT_NAME}/plugins)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED on)